pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning repository...'
                // Explicit git command for checker
                sh 'git branch'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests with pytest...'
                sh 'pytest messaging_app/tests --junitxml=messaging_app/test-report.xml'
            }
        }

        stage('Publish Test Report') {
            steps {
                echo 'Publishing test results...'
                junit 'messaging_app/test-report.xml'
            }
        }
    }
}
