pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning repository using credentials...'
                git url: 'https://github.com/Dama5323/alx-backend-python.git', branch: 'main', credentialsId: 'github-creds'
                sh 'git branch'
            }
        }

        stage('Install Python and Dependencies') {
            steps {
                echo 'Installing Python and dependencies...'
                sh '''
                    apt-get update
                    apt-get install -y python3 python3-pip python3-venv
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests with pytest...'
                sh 'pytest messaging_app/tests --junitxml=messaging_app/test-report.xml'
            }
        }

        stage('Publish Test Report') {
            steps {
                echo 'Publishing test results...'
                junit 'messaging_app/test-report.xml'
            }
        }
    }
}
